### ISSUE TITLE
Linking fail : Cannot find symbols error

### ISSUE THREAD

**Issue by asnagni** [MartinPerry/icu-build-scripts#2]
Hi,
  I was wondering if you could help with an issue I'm having with your scripts. After building the libraries and integrating them into my project I'm having a link error form Xcode. After checking, I can confirm that that the class "UnicodeString" is define. Would know how address this issue. Please see below:

Undefined symbol: vtable for icu_64::UObject
Undefined symbol: vtable for icu_64::Replaceable
Undefined symbol: vtable for icu_64::UnicodeString
Undefined symbol: icu_64::UnicodeString::~UnicodeString()
  

Thank you,
Stay safe.

**Comment by MartinPerry** [comment]
Hi, I am not sure what is wrong, I have never encountered such problem. Have you link the correct library (platform / version)?

**Comment by asnagni** [comment]
Hi Martin,
	Thank you for your reply, I do appreciate. 
	That is very strange. I downloaded the project and just changed in the prefix.sh file the base ICU directirectory and the the Android NDK root directory parameters. These are my specific information:
	export BASE_ICU_DIR="/Users/asnagni/project/temp/icu/icu-build-scripts/64”
	export ANDROID_NDK_ROOT="/Users/asnagni/Library/Android/sdk/ndk/21.3.6528147"

	beside these two parameters I do not change anything else.

After these 2 changes I performed theses steps:
	1) ran the Mac script in the mac directory:  ./build_icu_mac.sh
	2) ran the Android script in the android folder: ./build.sh
	3) ran the iOS script in the iOS folder: ./build-universal.sh

After completing building the libraries, I toke the include files and the libraries in the "ios-install” folder and include them into my project. Since I build the universal lib version, I should not have a version problem, isn’t it? Please let me know if I missed something in theses steps.

I’m using Xcode 12.3 I’m not sure if that could be the issue. Do you think that the  “CFLAGS” in the prefix.sh file should be change?


Thank you very much for helping on this.
Stay safe.

**Comment by asnagni** [comment]
Hi Martin,
	After spending some time checking everything it turns out that you are right. After compiling the latest version that was causing the issues, the include folder was not updated. The result was that the library ant the header files were not longer in sync.

	So the reason learn here is: after any update of the “prefix.sh” file, make sure to update the library and the header files in your project .

Thank you again,
Stay safe.
